### ISSUE TITLE
Compilation Error when linking

### ISSUE THREAD

**Issue by maximiliangoettgens** [loicland/cut-pursuit#12]
Cut-pursuit does not compile anymore since the last commit. 

Compiler is:

> gcc (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4

Error is:

`Scanning dependencies of target cp
[ 50%] Building CXX object CMakeFiles/cp.dir/cutpursuit.cpp.o
/home/max/superpoint_graph/partition/cut-pursuit/src/cutpursuit.cpp:9:28: fatal error: ../include/API.h: No such file or directory
 #include <../include/API.h>
                            ^
compilation terminated.
make[2]: *** [CMakeFiles/cp.dir/cutpursuit.cpp.o] Error 1
make[1]: *** [CMakeFiles/cp.dir/all] Error 2
make: *** [all] Error 2
`

(By the way in your SPG framework, do not forget to change the Readme to run cmake in cut-pursuit/src directory)

Best,
Max

**Comment by loicland** [comment]
Good catch, just fixed both.
