### ISSUE TITLE
Spatial flag does not seem to do anything

### ISSUE THREAD

**Issue by nicolas-chaulet** [loicland/cut-pursuit#20]
@loicland I don't see any difference between the two calls in this if/then/else is that correct?
https://github.com/loicland/cut-pursuit/blob/bb4afadab531aca825cc2e7ebd250e1da5e9a5da/src/cutpursuit.cpp#L94-L105

**Comment by loicland** [comment]
I fixed it.

`spatial==1` is an experimental mode, in which some values of the vertex variables (the last 3, which should be xyz) are treated differently when performing the reduction phase. It helps a little bit for superpoints oversegmentation, but is not extensively tested yet.
