### ISSUE TITLE
compile error with vs2017 

### ISSUE THREAD

**Issue by sjwfzu2016** [loicland/cut-pursuit#27]
Hi,doctor
I met a problem when compile cut-pursuit with VS2017, boost1.69,python3.6   
this is the problem:
cutpursuit.obj : error LNK2001    Unresolved external symbol  
struct boost::python::type_info __cdecl boost::python::detail::unwind_type<struct boost::python::converter::detail::unwind_type_id_helper,class boost::python::numpy::ndarray *>(class boost::python::numpy::ndarray * const &,struct boost::python::converter::detail::unwind_type_id_helper *)" (??$unwind_type@Uunwind_type_id_helper

**Comment by loicland** [comment]
You are compiling directly with VS? Did you make sure to include all source files?

[This](https://stackoverflow.com/a/9928307) stack thread seems relevant.

**Comment by sjwfzu2016** [comment]
I Modifed the unwind_type.h,then it work. thank you !
